# Generated by Django 5.2.11 on 2026-02-18 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('client', 'Client'), ('company', 'Company'), ('internship', 'Internship'), ('academy', 'Academy')], max_length=20)),
                ('work_type', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group')], max_length=10)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('ongoing', 'Ongoing'), ('on_hold', 'On Hold'), ('canceled', 'Canceled'), ('finished', 'Finished')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dashboard.department')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(choices=[('staff', 'Staff'), ('intern', 'Intern')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('date_of_join', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='workers/')),
                ('posting', models.CharField(max_length=150)),
                ('department_role', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='dashboard.department')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('copper', 'Copper')], max_length=10)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dashboard.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='dashboard.worker')),
            ],
            options={
                'unique_together': {('project', 'worker')},
            },
        ),
    ]
