# Generated by Django 5.2.11 on 2026-02-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_department_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='payment',
        ),
    ]
