# Generated by Django 5.2.11 on 2026-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_worker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='contribution',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('copper', 'Copper')], default='gold', max_length=10),
        ),
    ]
