# Generated by Django 5.2.11 on 2026-02-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_projectmember_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='working_status',
            field=models.CharField(choices=[('joind', 'Joined'), ('on board', 'On Board'), ('relived', 'Relived')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
